"use client"

// import type { Metadata } from "next";
import { useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar"
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";


const inter = Inter({ subsets: ["latin"] });

const disableNavbar = ["/login", "/register"];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [state, setState] = useState(0);
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        
          <SessionProvider>
          {/* // misal pathaname ada d login/register maka navbar tidak ditampilkan */}
          {!disableNavbar.includes(pathname) && <Navbar/>}
          {children}
          </SessionProvider>
   
       
      </body>
    </html>
  );
}
